server:
  port: 9002

spring:
  redis:
    host: localhost
    port: 6379
    password: root

  application:
    name: msa-weather-collection-eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/