spring:
  application:
    name: mirco-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PonKing66/springcloud-config.git
          search-paths: springcloud-weather-config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8787
